version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: acs_redis
    restart: always

  nginx:
    build: .
    container_name: acs_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres
      - backend
    volumes:
      - ./backend/static:/usr/src/app/static

  postgres:
    image: postgres:16
    container_name: acs_postgressql
    restart: always
    environment:
      - POSTGRES_DB=ACS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: acs_backend
    restart: always
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend/static:/usr/src/app/static
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=TURE
      - MODE=PROD

volumes:
  postgres-data:
