<script setup>
import { userLogSelectItem } from '@/utils/filter-select-item'
</script>

<template>
  <VCard
    elevation="3"
    rounded="3"
    title="Filters"
  >
    <VCardText>
      <VRow>
        <VCol
          cols="12"
          sm="3"
        >
          <VSelect
            label="請選擇事件"
            :items="userLogSelectItem"
            item-title="name"
            item-value="value"
            placeholder="請選擇事件"
            prepend-inner-icon="mdi-gesture-tap"
            variant="outlined"
            density="compact"
          />
        </VCol>
        <VCol
          cols="12"
          sm="5"
        >
          <VTextField
            label="搜尋創建日期"
            hide-details
            variant="outlined"
            density="compact"
            readonly
            placeholder="搜尋創建日期"
            prepend-inner-icon="mdi-calendar-outline"
          />
        </VCol>
        <VCol
          cols="12"
          sm="2"
        >
          <v-btn
            block
            color="primary"
            type="button"
            height="44"
          >
            Search
          </v-btn>
        </VCol>
        <VCol
          cols="12"
          sm="2"
        >
          <VBtn
            block
            color="error"
            variant="outlined"
            height="44"
          >
            Reset
          </VBtn>
        </VCol>
      </VRow>
    </VCardText>
  </VCard>
</template>
